name: Release Insiders

on:
  push:
    branches:
      - develop
    paths:
      - "packages/lapikit/**"

env:
  NODE_VERSION: "20"
  RELEASE_CHANNEL: insiders
  VERSION: 0.0.0
  PACKAGE_NAME: lapikit

permissions:
  id-token: write
  contents: read

jobs:
  prerelease:
    name: set insiders version
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: write
    outputs:
      version_release: ${{ steps.set_version.outputs.version_release }}
      sha_short: ${{ steps.get_sha_version.outputs.sha_version }}

    steps:
      - uses: actions/checkout@v4

      - name: resolve version
        id: get_sha_version
        run: |
          echo "sha_version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: generate version
        id: set_version
        run: |
          sha_version="${{ steps.get_sha_version.outputs.sha_version }}"
          echo "version_release=${VERSION}-${RELEASE_CHANNEL}.${sha_version}" >> $GITHUB_OUTPUT

  publish:
    name: build and publish
    runs-on: ubuntu-latest
    needs: prerelease
    env:
      version_release: ${{ needs.prerelease.outputs.version_release }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1.2.2

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org/"

      - name: update .npmrc
        run: |
          echo "engine-strict=false" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: install dependencies
        run: bun install

      - name: set insiders version in package.json
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version ${{ env.version_release }} -f

      - name: build package
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          bun run build

      - name: verify package
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          npm pack --dry-run

      - name: publish to npm
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          echo "Publishing version ${{ env.version_release }}"
          npm publish --tag ${{ env.RELEASE_CHANNEL }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
